# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish to NPM

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn run lint
      - run: yarn run test
      - run: yarn run build
      - run: yarn run test-build-result
      - run: yarn config set npmAuthToken ${{secrets.NPM_TOKEN}}
      - run: yarn workspace connect-miniprogram npm publish
